### ISSUE TITLE
First demo program (local_chat_demo.cpp) leaks memory like a sieve

### ISSUE THREAD

**Issue by tgill880** [connectivecpp/chops-net-ip#14]
**Describe the bug**
When the program successfully exits, there are multiple memory allocations that have not been deallocated.

**To Reproduce**
g++ -std=c++17 -g3 -fsanitize=address (etc)
OR
valgrind --tool=memcheck --leak-check=yes ./a.out

**Expected behavior**
No memory leaks should be present

**Desktop:**
 - OS: [Ubuntu Linux 13.04]
 - Compiler [g++ 7.3]
 - Version [1.0]

**Comment by cliffg-softwarelibre** [comment]
As an added data point, I'm going to add the sanitizer flags to the CMakefile configuration (conditionally if I can, unconditionally if needed for now), build and run all of the unit tests. Previously, using the Networking TS lib, all of the unit tests ran under the g++ sanitizer without any problems.

**Comment by tgill880** [comment]
Fixed, but needs to be handled by the chops-net-ip library.
